# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e15fc1cdcc39e4c19a721098e3f554076b3ac5f6129287a353e41bf1f2a824e000f5bd5e46f9e3d01eb24e3b2e8fcddd4171eb735afd9febf071f47a62a9c9

test:
  secret_key_base: e002e2224d1e8c5893520ba22e82ebc52fd266f768b7fe73be2d33a1b3f88c45a1b3d7345ffe2f7807f9c5f1b14b534627f7993435d61afcb65a8fda2e0e2098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
